<a href="https://colab.research.google.com/github/Parth7/ML-for-finance/blob/main/Naive_Bayes_Classifier_ES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving logistic data.csv to logistic data.csv


In [ ]:
import pandas as pd
dataset = pd.read_csv('logistic data.csv') 
X = dataset.iloc[:, [1]].values
y = dataset.iloc[:, -2].values

In [ ]:
print(X.shape, y.shape)
print(X[:5])
print(y[:5])

(10000, 1) (10000,)
[[2.111112]
 [2.112977]
 [2.111623]
 [2.11149 ]
 [2.109245]]
[1 1 1 1 1]


In [ ]:
import numpy as np
from scipy.stats import norm
def fit_distribution(data):
  # estimate parameters
  mu = np.mean(data)
  sigma = np.std(data)
  #print(mu, sigma)
  # fit distribution
  dist = norm(mu, sigma)
  return dist

In [ ]:
Xy = np.zeros((50,200))

In [ ]:
Xy.shape

(50, 200)

In [ ]:
Xy[1][199]

0.0

In [ ]:
X[y == 49][0]

array([1.220234])

In [ ]:
for i in range(50):
    for j in range(0,200):
      Xy[i][j] = X[y == i+1][j]

In [ ]:
Xy[48][0]

1.220234

In [ ]:
Xy49[0]

NameError: ignored

In [ ]:
priory = np.zeros(50)

for i in range(50):
  priory[i] = len(Xy[i])/len(X)

In [ ]:
print(priory[30])

0.02


In [ ]:
def probability(X, prior, dist1):
	return prior * dist1.pdf(X[0])

In [ ]:
Xy[i].mean()

2.12031452

In [ ]:
fit_distribution(Xy[1])

2.16078444 0.0012923816372883109


In [ ]:
distXy = []
for i in range(50):
  distXy.append(fit_distribution(Xy[i]))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)
  
# training the model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
# classify one example
py = np.zeros((50,1))
Xsample, ysample = X[0], y[0]

for i in range(50):
  py[i] = probability(Xsample, priory[i], distXy[i])

for i in range(50):
  print('P(y=%d | %s) = %.3f' % (i+1,Xsample, py[i]*100))

print('Truth: y=%d' % ysample)

P(y=1 | [2.111112]) = 306.909
P(y=2 | [2.111112]) = 0.000
P(y=3 | [2.111112]) = 0.000
P(y=4 | [2.111112]) = 0.000
P(y=5 | [2.111112]) = 0.000
P(y=6 | [2.111112]) = 0.000
P(y=7 | [2.111112]) = 0.000
P(y=8 | [2.111112]) = 0.000
P(y=9 | [2.111112]) = 0.000
P(y=10 | [2.111112]) = 0.000
P(y=11 | [2.111112]) = 0.000
P(y=12 | [2.111112]) = 0.000
P(y=13 | [2.111112]) = 0.000
P(y=14 | [2.111112]) = 0.000
P(y=15 | [2.111112]) = 0.000
P(y=16 | [2.111112]) = 0.000
P(y=17 | [2.111112]) = 0.000
P(y=18 | [2.111112]) = 0.000
P(y=19 | [2.111112]) = 0.000
P(y=20 | [2.111112]) = 0.000
P(y=21 | [2.111112]) = 0.000
P(y=22 | [2.111112]) = 0.000
P(y=23 | [2.111112]) = 0.000
P(y=24 | [2.111112]) = 0.000
P(y=25 | [2.111112]) = 0.000
P(y=26 | [2.111112]) = 0.000
P(y=27 | [2.111112]) = 0.000
P(y=28 | [2.111112]) = 0.000
P(y=29 | [2.111112]) = 0.000
P(y=30 | [2.111112]) = 0.000
P(y=31 | [2.111112]) = 0.000
P(y=32 | [2.111112]) = 0.000
P(y=33 | [2.111112]) = 0.000
P(y=34 | [2.111112]) = 0.000
P(y=35 | [2.111112]) 

In [ ]:
# classify one example
py = np.zeros((50,1))
Xsample, ysample = X[2764], y[2764]

for i in range(50):
  py[i] = probability(Xsample, priory[i], distXy[i])

for i in range(50):
  print('P(y=%d | %s) = %.3f' % (i+1,Xsample, py[i]*100))

print('Truth: y=%d' % ysample)

P(y=1 | [2.727806]) = 0.000
P(y=2 | [2.727806]) = 0.000
P(y=3 | [2.727806]) = 0.000
P(y=4 | [2.727806]) = 0.000
P(y=5 | [2.727806]) = 0.000
P(y=6 | [2.727806]) = 0.000
P(y=7 | [2.727806]) = 0.000
P(y=8 | [2.727806]) = 0.000
P(y=9 | [2.727806]) = 0.000
P(y=10 | [2.727806]) = 0.000
P(y=11 | [2.727806]) = 0.000
P(y=12 | [2.727806]) = 0.000
P(y=13 | [2.727806]) = 0.000
P(y=14 | [2.727806]) = 391.762
P(y=15 | [2.727806]) = 0.000
P(y=16 | [2.727806]) = 0.000
P(y=17 | [2.727806]) = 0.000
P(y=18 | [2.727806]) = 0.000
P(y=19 | [2.727806]) = 0.000
P(y=20 | [2.727806]) = 0.000
P(y=21 | [2.727806]) = 0.000
P(y=22 | [2.727806]) = 0.000
P(y=23 | [2.727806]) = 0.000
P(y=24 | [2.727806]) = 0.000
P(y=25 | [2.727806]) = 0.000
P(y=26 | [2.727806]) = 0.000
P(y=27 | [2.727806]) = 0.000
P(y=28 | [2.727806]) = 0.000
P(y=29 | [2.727806]) = 0.000
P(y=30 | [2.727806]) = 0.000
P(y=31 | [2.727806]) = 0.000
P(y=32 | [2.727806]) = 0.000
P(y=33 | [2.727806]) = 0.000
P(y=34 | [2.727806]) = 0.000
P(y=35 | [2.727806]) 

In [ ]:
# classify one example
py = np.zeros((50,1))
Xsample, ysample = X[764], y[764]

for i in range(50):
  py[i] = probability(Xsample, priory[i], distXy[i])

for i in range(50):
  print('P(y=%d | %s) = %.3f' % (i+1,Xsample, py[i]*100))

print('Truth: y=%d' % ysample)

P(y=1 | [2.337729]) = 0.000
P(y=2 | [2.337729]) = 0.000
P(y=3 | [2.337729]) = 0.000
P(y=4 | [2.337729]) = 294.672
P(y=5 | [2.337729]) = 0.000
P(y=6 | [2.337729]) = 0.000
P(y=7 | [2.337729]) = 0.000
P(y=8 | [2.337729]) = 0.000
P(y=9 | [2.337729]) = 0.000
P(y=10 | [2.337729]) = 0.000
P(y=11 | [2.337729]) = 0.000
P(y=12 | [2.337729]) = 0.000
P(y=13 | [2.337729]) = 0.000
P(y=14 | [2.337729]) = 0.000
P(y=15 | [2.337729]) = 0.000
P(y=16 | [2.337729]) = 0.000
P(y=17 | [2.337729]) = 0.000
P(y=18 | [2.337729]) = 0.000
P(y=19 | [2.337729]) = 0.000
P(y=20 | [2.337729]) = 0.000
P(y=21 | [2.337729]) = 0.000
P(y=22 | [2.337729]) = 0.000
P(y=23 | [2.337729]) = 0.000
P(y=24 | [2.337729]) = 0.000
P(y=25 | [2.337729]) = 0.000
P(y=26 | [2.337729]) = 0.000
P(y=27 | [2.337729]) = 0.000
P(y=28 | [2.337729]) = 0.000
P(y=29 | [2.337729]) = 0.000
P(y=30 | [2.337729]) = 0.000
P(y=31 | [2.337729]) = 0.000
P(y=32 | [2.337729]) = 0.000
P(y=33 | [2.337729]) = 0.000
P(y=34 | [2.337729]) = 0.000
P(y=35 | [2.337729]) 

In [ ]:
from random import randint
value = randint(0,10000)

In [ ]:
# classify 5 example
count = 0
for j in range(10000):
  py = {}
  Xsample, ysample = X[j], y[j]
  for i in range(50):
    py[i] = probability(Xsample, priory[i], distXy[i])

  #for i in range(50):
    #print('P(y=%d | %s) = %.3f' % (i+1,Xsample, py[i]*100))

  a = np.array(sorted(py, key=py.get, reverse=True)[:5])+1

  for k in range(5):
    if(ysample==a[k]):
      count+=1

In [ ]:
count/10000 *100

99.97

In [ ]:
# classify one example
count = 0
for j in range(10000):
  py = {}
  Xsample, ysample = X[j], y[j]
  for i in range(50):
    py[i] = probability(Xsample, priory[i], distXy[i])

  #for i in range(50):
    #print('P(y=%d | %s) = %.3f' % (i+1,Xsample, py[i]*100))

  a = np.array(sorted(py, key=py.get, reverse=True)[:1])+1

  for k in range(1):
    if(ysample==a[k]):
      count+=1

In [ ]:
count/10000 *100

84.59