<a href="https://colab.research.google.com/github/Parth7/ML-for-finance/blob/main/Naive_Bayes_Classifier_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [226]:
from google.colab import files
uploaded = files.upload()

Saving cummulative_data_complete_corrected.xlsx to cummulative_data_complete_corrected (1).xlsx


In [227]:
import pandas as pd
dataset = pd.read_excel('cummulative_data_complete_corrected.xlsx') 
X = dataset.iloc[:, [0]].values
y = dataset.iloc[:, -1].values

In [228]:
print(X.shape, y.shape)
print(X[:5])
print(y[:5])

(10000, 1) (10000,)
[[13.992114]
 [13.930585]
 [13.809978]
 [13.911977]
 [13.810281]]
[1 1 1 1 1]


In [253]:
import numpy as np
from scipy.stats import norm
def fit_distribution(data):
  # estimate parameters
  mu = np.mean(data)
  sigma = np.std(data)
  #print(mu, sigma)
  # fit distribution
  dist = norm(mu, sigma)
  return dist

In [230]:
Xy = np.zeros((50,200))

In [231]:
Xy.shape

(50, 200)

In [232]:
Xy[1][199]

0.0

In [233]:
X[y == 49][0]

array([5.80504441])

In [234]:
for i in range(50):
    for j in range(0,200):
      Xy[i][j] = X[y == i+1][j]

In [235]:
Xy[48][0]

5.805044411

In [236]:
Xy49[0]

array([5.80504441])

In [237]:
priory = np.zeros(50)

for i in range(50):
  priory[i] = len(Xy[i])/len(X)

In [238]:
print(priory[30])

0.02


In [239]:
def probability(X, prior, dist1):
	return prior * dist1.pdf(X[0])

In [242]:
Xy[i].mean()

13.967048135

In [246]:
fit_distribution(Xy[1])

15.2138302 0.5442985028361828


In [255]:
distXy = []
for i in range(50):
  distXy.append(fit_distribution(Xy[i]))

In [257]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)
  
# training the model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [256]:
# classify one example
py = np.zeros((50,1))
Xsample, ysample = X[0], y[0]

for i in range(50):
  py[i] = probability(Xsample, priory[i], distXy[i])

for i in range(50):
  print('P(y=%d | %s) = %.3f' % (i+1,Xsample, py[i]*100))

print('Truth: y=%d' % ysample)

P(y=1 | [13.992114]) = 8.388
P(y=2 | [13.992114]) = 0.118
P(y=3 | [13.992114]) = 0.000
P(y=4 | [13.992114]) = 0.000
P(y=5 | [13.992114]) = 0.000
P(y=6 | [13.992114]) = 0.000
P(y=7 | [13.992114]) = 0.138
P(y=8 | [13.992114]) = 0.000
P(y=9 | [13.992114]) = 0.000
P(y=10 | [13.992114]) = 0.000
P(y=11 | [13.992114]) = 0.000
P(y=12 | [13.992114]) = 0.159
P(y=13 | [13.992114]) = 0.000
P(y=14 | [13.992114]) = 0.000
P(y=15 | [13.992114]) = 0.027
P(y=16 | [13.992114]) = 0.000
P(y=17 | [13.992114]) = 0.171
P(y=18 | [13.992114]) = 0.000
P(y=19 | [13.992114]) = 0.000
P(y=20 | [13.992114]) = 0.065
P(y=21 | [13.992114]) = 0.000
P(y=22 | [13.992114]) = 0.099
P(y=23 | [13.992114]) = 0.000
P(y=24 | [13.992114]) = 0.000
P(y=25 | [13.992114]) = 0.000
P(y=26 | [13.992114]) = 0.000
P(y=27 | [13.992114]) = 0.046
P(y=28 | [13.992114]) = 0.002
P(y=29 | [13.992114]) = 0.002
P(y=30 | [13.992114]) = 0.000
P(y=31 | [13.992114]) = 0.000
P(y=32 | [13.992114]) = 0.005
P(y=33 | [13.992114]) = 2.537
P(y=34 | [13.992114

In [259]:
# classify one example
py = np.zeros((50,1))
Xsample, ysample = X[2764], y[2764]

for i in range(50):
  py[i] = probability(Xsample, priory[i], distXy[i])

for i in range(50):
  print('P(y=%d | %s) = %.3f' % (i+1,Xsample, py[i]*100))

print('Truth: y=%d' % ysample)

P(y=1 | [15.67899]) = 0.000
P(y=2 | [15.67899]) = 1.017
P(y=3 | [15.67899]) = 0.021
P(y=4 | [15.67899]) = 0.000
P(y=5 | [15.67899]) = 1.716
P(y=6 | [15.67899]) = 0.000
P(y=7 | [15.67899]) = 0.997
P(y=8 | [15.67899]) = 0.000
P(y=9 | [15.67899]) = 0.000
P(y=10 | [15.67899]) = 3.728
P(y=11 | [15.67899]) = 0.000
P(y=12 | [15.67899]) = 0.895
P(y=13 | [15.67899]) = 0.000
P(y=14 | [15.67899]) = 0.000
P(y=15 | [15.67899]) = 1.389
P(y=16 | [15.67899]) = 0.000
P(y=17 | [15.67899]) = 0.828
P(y=18 | [15.67899]) = 0.000
P(y=19 | [15.67899]) = 0.000
P(y=20 | [15.67899]) = 1.246
P(y=21 | [15.67899]) = 0.000
P(y=22 | [15.67899]) = 1.086
P(y=23 | [15.67899]) = 0.000
P(y=24 | [15.67899]) = 0.000
P(y=25 | [15.67899]) = 3.988
P(y=26 | [15.67899]) = 0.000
P(y=27 | [15.67899]) = 1.273
P(y=28 | [15.67899]) = 0.000
P(y=29 | [15.67899]) = 0.000
P(y=30 | [15.67899]) = 0.663
P(y=31 | [15.67899]) = 0.000
P(y=32 | [15.67899]) = 1.114
P(y=33 | [15.67899]) = 0.000
P(y=34 | [15.67899]) = 0.000
P(y=35 | [15.67899]) = 

In [260]:
# classify one example
py = np.zeros((50,1))
Xsample, ysample = X[764], y[764]

for i in range(50):
  py[i] = probability(Xsample, priory[i], distXy[i])

for i in range(50):
  print('P(y=%d | %s) = %.3f' % (i+1,Xsample, py[i]*100))

print('Truth: y=%d' % ysample)

P(y=1 | [10.89075]) = 0.000
P(y=2 | [10.89075]) = 0.000
P(y=3 | [10.89075]) = 0.000
P(y=4 | [10.89075]) = 0.000
P(y=5 | [10.89075]) = 0.000
P(y=6 | [10.89075]) = 0.000
P(y=7 | [10.89075]) = 0.000
P(y=8 | [10.89075]) = 0.000
P(y=9 | [10.89075]) = 0.000
P(y=10 | [10.89075]) = 0.000
P(y=11 | [10.89075]) = 0.000
P(y=12 | [10.89075]) = 0.000
P(y=13 | [10.89075]) = 0.000
P(y=14 | [10.89075]) = 0.000
P(y=15 | [10.89075]) = 0.000
P(y=16 | [10.89075]) = 2.923
P(y=17 | [10.89075]) = 0.000
P(y=18 | [10.89075]) = 0.000
P(y=19 | [10.89075]) = 0.000
P(y=20 | [10.89075]) = 0.000
P(y=21 | [10.89075]) = 0.000
P(y=22 | [10.89075]) = 0.000
P(y=23 | [10.89075]) = 0.000
P(y=24 | [10.89075]) = 0.000
P(y=25 | [10.89075]) = 0.000
P(y=26 | [10.89075]) = 0.000
P(y=27 | [10.89075]) = 0.000
P(y=28 | [10.89075]) = 0.000
P(y=29 | [10.89075]) = 0.000
P(y=30 | [10.89075]) = 0.000
P(y=31 | [10.89075]) = 0.000
P(y=32 | [10.89075]) = 0.000
P(y=33 | [10.89075]) = 0.000
P(y=34 | [10.89075]) = 0.044
P(y=35 | [10.89075]) = 

In [269]:
from random import randint
value = randint(0,10000)

In [288]:
# classify one example
count = 0
for j in range(10000):
  py = {}
  Xsample, ysample = X[j], y[j]
  for i in range(50):
    py[i] = probability(Xsample, priory[i], distXy[i])

  #for i in range(50):
    #print('P(y=%d | %s) = %.3f' % (i+1,Xsample, py[i]*100))

  a = np.array(sorted(py, key=py.get, reverse=True)[:5])+1

  for k in range(5):
    if(ysample==a[k]):
      count+=1

In [290]:
count/10000 *100

84.43