<a href="https://colab.research.google.com/github/Parth7/ML-for-finance/blob/main/NN_VAR_data_Nevena_model_1_reversed_with_classes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

# Commonly used modules
import numpy as np
import os
import sys

# Images, plots, display, and visualization
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import cv2
import IPython
from six.moves import urllib
import random
print(tf.__version__)

2.5.0


In [2]:
from google.colab import files
uploaded = files.upload()

Saving cummulative_data_NN2.xls to cummulative_data_NN2.xls


In [3]:
file = pd.read_excel('cummulative_data_NN2.xls') 
# Data for three-dimensional scattered points


#(train_features, train_labels), (test_features, test_labels) = keras.datasets.boston_housing.load_data()

# get per-feature statistics (mean, standard deviation) from the training set to normalize by
#train_mean = np.mean(train_features, axis=0)
#train_std = np.std(train_features, axis=0)
#train_features = (train_features - train_mean) / train_std

In [4]:
file = file.to_numpy()

In [5]:
file[:10]

array([[13.99,  1.  ,   nan,   nan,   nan,   nan],
       [13.93,  1.  ,   nan,   nan,   nan,   nan],
       [13.81,  1.  ,   nan,   nan,   nan,   nan],
       [13.91,  1.  ,   nan,   nan,   nan,   nan],
       [13.81,  1.  ,   nan,   nan,   nan,   nan],
       [13.96,  1.  ,   nan,   nan,   nan,   nan],
       [14.06,  1.  ,   nan,   nan,   nan,   nan],
       [13.99,  1.  ,   nan,   nan,   nan,   nan],
       [13.92,  1.  ,   nan,   nan,   nan,   nan],
       [13.95,  1.  ,   nan,   nan,   nan,   nan]])

In [6]:
np.random.shuffle(file) 

In [7]:
file[:10]

array([[ 5.83, 49.  ,   nan,   nan,   nan,   nan],
       [15.56, 10.  ,   nan,   nan,   nan,   nan],
       [18.83,  4.  ,   nan,   nan,   nan,   nan],
       [11.85, 11.  ,   nan,   nan,   nan,   nan],
       [ 5.85, 49.  ,   nan,   nan,   nan,   nan],
       [15.37, 25.  ,   nan,   nan,   nan,   nan],
       [ 7.46, 44.  ,   nan,   nan,   nan,   nan],
       [13.  , 38.  ,   nan,   nan,   nan,   nan],
       [10.4 , 21.  ,   nan,   nan,   nan,   nan],
       [22.14, 36.  ,   nan,   nan,   nan,   nan]])

In [8]:
file[:,0]

array([ 5.83, 15.56, 18.83, ..., 27.45, 15.27, 15.86])

In [9]:
zdata = file[:,0]
xdata = file[:,1]

data = np.array([xdata])
zd = np.array([zdata])

In [10]:
data[:,56]

array([10.])

In [11]:
d = np.zeros(data.size)
for i in range(data.size):
  d[i] = int(data[:,i])

In [12]:
int(d[45])

18

In [13]:
d = pd.get_dummies(d)

In [14]:
d

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
0        0     0     0     0     0     0  ...     0     0     0     0     1     0
1        0     0     0     0     0     0  ...     0     0     0     0     0     0
2        0     0     0     1     0     0  ...     0     0     0     0     0     0
3        0     0     0     0     0     0  ...     0     0     0     0     0     0
4        0     0     0     0     0     0  ...     0     0     0     0     1     0
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
9995     0     0     0     0     0     0  ...     0     0     0     0     0     0
9996     0     1     0     0     0     0  ...     0     0     0     0     0     0
9997     0     0     0     0     0     0  ...     0     0     0     0     0     0
9998     0     0     0     0     0     0  ...     0     0     0     0     0     0
9999     0     0     0     0     0     0  ...     0     0     0     0     0     0

[10000 rows x 50 columns]

In [15]:
data = d

In [16]:
#zd = (zd-zd.min())/(zd.max())

In [17]:
zd[:5]

array([[ 5.83, 15.56, 18.83, ..., 27.45, 15.27, 15.86]])

In [18]:
data[:5]

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
0     0     0     0     0     0     0  ...     0     0     0     0     1     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     1     0     0  ...     0     0     0     0     0     0
3     0     0     0     0     0     0  ...     0     0     0     0     0     0
4     0     0     0     0     0     0  ...     0     0     0     0     1     0

[5 rows x 50 columns]

In [19]:
data[:8000].shape

(8000, 50)

In [20]:
test_set_size = int(np.round(0.2*data.shape[1]));
train_set_size = data.shape[1] - (test_set_size);

In [21]:
x_train = data[:8000]
y_train = zd[:,:8000]

x_test = data[8000:]
y_test = zd[:,8000:]

In [22]:
x_train.shape

(8000, 50)

In [23]:
y_train.T.shape

(8000, 1)

In [24]:
x_train.shape

(8000, 50)

In [25]:
x_train = x_train
y_train = y_train.T
x_test = x_test
y_test = y_test.T

In [26]:
y_train.shape[1]

1

In [30]:
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.constraints import maxnorm
from keras.optimizers import Adam
from keras.layers.core import Dense, Dropout, Activation
'''
#build our model
model = Sequential()

model.add(Dense(25, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='Adam')

#build our model
model = Sequential()
model.add(Dense(250,input_dim=y_train.shape[1],kernel_initializer='normal', activation='relu'))
model.add(Dense(500,kernel_initializer='normal', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(250,kernel_initializer='normal', activation='relu'))
model.add(Dense(50,activation='softmax'))
# Compile model
optimizer = Adam(learning_rate=0.01, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
#optimizer = SGD(learning_rate=0.01, momentum=0)

'''

model = Sequential()
model.add(Dense(50,input_dim=y_train.shape[1]))
model.add(Activation('relu'))
model.add(Dense(500))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(50))
model.add(Activation('softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 50)                100       
_________________________________________________________________
activation_3 (Activation)    (None, 50)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 500)               25500     
_________________________________________________________________
activation_4 (Activation)    (None, 500)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 500)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 50)                25050     
_________________________________________________________________
activation_5 (Activation)    (None, 50)               

In [31]:
model.compile(loss='categorical_crossentropy', optimizer='ADAM', metrics=['accuracy'])

In [32]:
model.fit(y_train, x_train, batch_size=128, epochs=100,verbose=1)

Epoch 1/100
63/63 [==============================] - 1s 4ms/step - loss: 4.0026 - accuracy: 0.0240
Epoch 2/100
63/63 [==============================] - 0s 4ms/step - loss: 3.8826 - accuracy: 0.0147
Epoch 3/100
63/63 [==============================] - 0s 4ms/step - loss: 3.8305 - accuracy: 0.0205
Epoch 4/100
63/63 [==============================] - 0s 4ms/step - loss: 3.7756 - accuracy: 0.0409
Epoch 5/100
63/63 [==============================] - 0s 4ms/step - loss: 3.6601 - accuracy: 0.0537
Epoch 6/100
63/63 [==============================] - 0s 3ms/step - loss: 3.4545 - accuracy: 0.0656
Epoch 7/100
63/63 [==============================] - 0s 4ms/step - loss: 3.2224 - accuracy: 0.0956
Epoch 8/100
63/63 [==============================] - 0s 4ms/step - loss: 3.0107 - accuracy: 0.1251
Epoch 9/100
63/63 [==============================] - 0s 4ms/step - loss: 2.8543 - accuracy: 0.1589
Epoch 10/100
63/63 [==============================] - 0s 3ms/step - loss: 2.7293 - accuracy: 0.1718
Epoch 11/

In [33]:
x_test[0:1]

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
8000     0     0     0     0     0     0  ...     0     0     0     0     0     0

[1 rows x 50 columns]

In [ ]:
# Use scikit-learn to grid search the batch size and epochs
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
# Function to create model, required for KerasClassifier
def create_model():
  # create model
  model = Sequential()
  model.add(Dense(12, input_dim=y_train.shape[1], activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  # Compile model
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model


# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# define the grid search parameters
batch_size = [10, 20, 40, 60, 80, 100]
epochs = [10, 50, 100]
param_grid = dict(batch_size=batch_size, epochs=epochs)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(y_train,x_train)


# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

In [ ]:
# Use scikit-learn to grid search the learning rate and momentum
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.optimizers import Adam
# Function to create model, required for KerasClassifier
def create_model(learn_rate=0.01, momentum=0):
  # create model
  model = Sequential()
  model.add(Dense(25, input_dim=y_train.shape[1], activation='relu'))
  model.add(Dense(50, activation='relu'))
  model.add(Dense(25, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  # Compile model
  optimizer = Adam(lr=learn_rate, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
  model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
  return model

# create model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
learn_rate = [0.001, 0.01, 0.1, 0.2, 0.3]
param_grid = dict(learn_rate=learn_rate, momentum=momentum)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(y_train,x_train)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

In [34]:
score = model.evaluate(y_test,x_test)
print('Test score:', score[0])
print('Test accuracy:', score[1])

63/63 [==============================] - 1s 3ms/step - loss: 1.5509 - accuracy: 0.4680
Test score: 1.5508630275726318
Test accuracy: 0.46799999475479126


In [45]:
test_predictions = model.predict(y_test)

In [46]:
for i in range(10):
  print(test_predictions[i])
  print()

[0.   0.   0.   0.   0.   0.   0.   0.   0.77 0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.06 0.   0.   0.   0.   0.
 0.   0.   0.11 0.   0.   0.   0.   0.06 0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.  ]
[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.18 0.   0.   0.
 0.   0.02 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.37 0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.44 0.   0.  ]
[0.19 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.01
 0.26 0.   0.   0.   0.51 0.   0.   0.   0.   0.01 0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.  ]
[0.39 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.01 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.04
 0.04 0.   0.   0.   0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.  ]


In [ ]:
#from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D, GlobalAveragePooling2D, Flatten
from keras.layers.normalization import BatchNormalization

In [ ]:
model = Sequential()                                 # Linear stacking of layers

# Convolution Layer 1
model.add(Conv2D(32, (1, 1),input_dim=y_train.shape[1])) # 32 different 3x3 kernels -- so 32 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
convLayer01 = Activation('relu')                     # activation
model.add(convLayer01)

# Convolution Layer 2
model.add(Conv2D(32, (3, 3)))                        # 32 different 3x3 kernels -- so 32 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
model.add(Activation('relu'))                        # activation
convLayer02 = MaxPooling2D(pool_size=(2,2))          # Pool the max values over a 2x2 kernel
model.add(convLayer02)

# Convolution Layer 3
model.add(Conv2D(64,(3, 3)))                         # 64 different 3x3 kernels -- so 64 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
convLayer03 = Activation('relu')                     # activation
model.add(convLayer03)

# Convolution Layer 4
model.add(Conv2D(64, (3, 3)))                        # 64 different 3x3 kernels -- so 64 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
model.add(Activation('relu'))                        # activation
convLayer04 = MaxPooling2D(pool_size=(2,2))          # Pool the max values over a 2x2 kernel
model.add(convLayer04)
model.add(Flatten())                                 # Flatten final 4x4x64 output matrix into a 1024-length vector

# Fully Connected Layer 5
model.add(Dense(512))                                # 512 FCN nodes
model.add(BatchNormalization())                      # normalization
model.add(Activation('relu'))                        # activation

# Fully Connected Layer 6                       
model.add(Dropout(0.2))                              # 20% dropout of randomly selected nodes
model.add(Dense(10))                                 # final 10 FCN nodes
model.add(Activation('softmax'))                     # softmax activation

ValueError: ignored