In [2]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

# Commonly used modules
import numpy as np
import os
import sys

# Images, plots, display, and visualization
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import cv2
import IPython
from six.moves import urllib
import random
print(tf.__version__)

2.5.0


In [3]:
from google.colab import files
uploaded = files.upload()

Saving cummulative_data.xls to cummulative_data.xls


In [4]:
file = pd.read_excel('cummulative_data.xls') 
# Data for three-dimensional scattered points


#(train_features, train_labels), (test_features, test_labels) = keras.datasets.boston_housing.load_data()

# get per-feature statistics (mean, standard deviation) from the training set to normalize by
#train_mean = np.mean(train_features, axis=0)
#train_std = np.std(train_features, axis=0)
#train_features = (train_features - train_mean) / train_std

In [5]:
file = file.to_numpy()

In [6]:
file[:10]

array([[13.992114, 25.      , 10.      ],
       [13.930585, 25.      , 10.      ],
       [13.809978, 25.      , 10.      ],
       [13.911977, 25.      , 10.      ],
       [13.810281, 25.      , 10.      ],
       [13.961872, 25.      , 10.      ],
       [14.06189 , 25.      , 10.      ],
       [13.994377, 25.      , 10.      ],
       [13.922221, 25.      , 10.      ],
       [13.952919, 25.      , 10.      ]])

In [7]:
np.random.shuffle(file) 

In [8]:
file[:10]

array([[ 10.28289   ,  25.        ,  50.        ],
       [ 15.695962  ,  50.        ,  30.        ],
       [ 17.29240796,  75.        ,  20.        ],
       [ 15.595149  , 125.        ,  50.        ],
       [ 19.44251247,  75.        ,  50.        ],
       [ 13.07160879,  75.        , -30.        ],
       [ 11.08861   ,  25.        ,  40.        ],
       [ 17.05308784,  75.        ,  20.        ],
       [ 14.314553  , 125.        ,  40.        ],
       [ 11.15471787, 100.        , -20.        ]])

In [9]:
file[:,0]

array([10.28289   , 15.695962  , 17.29240796, ..., 15.668897  ,
       15.997301  , 13.46289686])

In [10]:
zdata = file[:,0]
xdata = file[:,1]
ydata = file[:,2]

data = np.array([xdata,ydata])
zd = np.array([zdata])

In [11]:
test_set_size = int(np.round(0.2*data.shape[1]));
train_set_size = data.shape[1] - (test_set_size);

In [12]:
x_train = data[:,:train_set_size]
y_train = zd[:,:train_set_size]

x_test = data[:,train_set_size:]
y_test = zd[:,train_set_size:]

In [13]:
x_train[:15]

array([[ 25.,  50.,  75., ..., 100.,  25.,  50.],
       [ 50.,  30.,  20., ..., -30.,  40., -20.]])

In [14]:
train_features = x_train

In [15]:
y_train.T.shape

(8000, 1)

In [16]:
x_train.T.shape

(8000, 2)

In [17]:
x_train = x_train.T
y_train = y_train.T
x_test = x_test.T
y_test = y_test.T

In [18]:
#Define training hyperprameters.
batch_size = 50
num_epochs = 200
learning_rate = 0.01
size_hidden= 20

#Calculate some other hyperparameters based on data.  
batch_no = len(x_train) // batch_size  #batches
cols=x_train.shape[1] #Number of columns in input matrix
n_output=1

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [20]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

#build our model
model = Sequential()

model.add(Dense(50, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model
model.fit(
    x_train,
    y_train,
    epochs=50,
    shuffle=True,
    verbose=2
)

Epoch 1/50
250/250 - 20s - loss: 32.9548
Epoch 2/50
250/250 - 0s - loss: 24.7683
Epoch 3/50
250/250 - 0s - loss: 17.3598
Epoch 4/50
250/250 - 0s - loss: 9.4288
Epoch 5/50
250/250 - 0s - loss: 7.4253
Epoch 6/50
250/250 - 0s - loss: 6.2903
Epoch 7/50
250/250 - 0s - loss: 6.4076
Epoch 8/50
250/250 - 0s - loss: 6.7399
Epoch 9/50
250/250 - 0s - loss: 5.8107
Epoch 10/50
250/250 - 0s - loss: 5.5018
Epoch 11/50
250/250 - 0s - loss: 5.4180
Epoch 12/50
250/250 - 0s - loss: 5.3846
Epoch 13/50
250/250 - 0s - loss: 4.7420
Epoch 14/50
250/250 - 0s - loss: 4.3313
Epoch 15/50
250/250 - 0s - loss: 4.1842
Epoch 16/50
250/250 - 0s - loss: 3.7057
Epoch 17/50
250/250 - 0s - loss: 4.1578
Epoch 18/50
250/250 - 0s - loss: 3.1606
Epoch 19/50
250/250 - 0s - loss: 2.8154
Epoch 20/50
250/250 - 0s - loss: 2.6474
Epoch 21/50
250/250 - 0s - loss: 2.1049
Epoch 22/50
250/250 - 0s - loss: 2.4462
Epoch 23/50
250/250 - 0s - loss: 1.6096
Epoch 24/50
250/250 - 0s - loss: 1.4197
Epoch 25/50
250/250 - 0s - loss: 1.3818
Epoch

In [40]:
x_test[1].T

array([25., 50.])

In [48]:
x_test[0:1]

array([[ 50., -30.]])

In [49]:
y_test[0:1]

array([[15.661248]])

In [51]:
a = [1,2,3,4,5,6,7,8,9];
for i in a: 
  prediction = model.predict(x_test[i-1:i])
  y_0 = prediction[0][0]
  print('Prediction - {}',format(y_0))
  print('Actual',y_test[i-1:i])

Prediction - {} 16.071331024169922
Actual [[15.661248]]
Prediction - {} 10.406280517578125
Actual [[10.23856]]
Prediction - {} 15.355934143066406
Actual [[15.45031698]]
Prediction - {} 31.606369018554688
Actual [[31.72248]]
Prediction - {} 15.166116714477539
Actual [[15.21339364]]
Prediction - {} 26.635093688964844
Actual [[27.4990951]]
Prediction - {} 14.936527252197266
Actual [[16.423049]]
Prediction - {} 12.013080596923828
Actual [[11.65747]]
Prediction - {} 16.62858772277832
Actual [[16.309662]]
