<a href="https://colab.research.google.com/github/Parth7/ML-for-finance/blob/main/NN_VAR_data_Nevena_model_1_reversed_with_25_classes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Commonly used modules
import numpy as np
import os
import sys

# Images, plots, display, and visualization
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import cv2
import IPython
from six.moves import urllib
import random
print(tf.__version__)

2.5.0


In [2]:
from google.colab import files
uploaded = files.upload()

Saving cummulative_data_NN3.xlsx to cummulative_data_NN3.xlsx


In [4]:
file = pd.read_excel('cummulative_data_NN3.xlsx') 
# Data for three-dimensional scattered points


#(train_features, train_labels), (test_features, test_labels) = keras.datasets.boston_housing.load_data()

# get per-feature statistics (mean, standard deviation) from the training set to normalize by
#train_mean = np.mean(train_features, axis=0)
#train_std = np.std(train_features, axis=0)
#train_features = (train_features - train_mean) / train_std

In [5]:
file = file.to_numpy()

In [6]:
file[:10]

array([[13.99,  1.  ,   nan,   nan,   nan,   nan],
       [13.93,  1.  ,   nan,   nan,   nan,   nan],
       [13.81,  1.  ,   nan,   nan,   nan,   nan],
       [13.91,  1.  ,   nan,   nan,   nan,   nan],
       [13.81,  1.  ,   nan,   nan,   nan,   nan],
       [13.96,  1.  ,   nan,   nan,   nan,   nan],
       [14.06,  1.  ,   nan,   nan,   nan,   nan],
       [13.99,  1.  ,   nan,   nan,   nan,   nan],
       [13.92,  1.  ,   nan,   nan,   nan,   nan],
       [13.95,  1.  ,   nan,   nan,   nan,   nan]])

In [7]:
np.random.shuffle(file) 

In [8]:
file[:10]

array([[27.05, 14.  ,   nan,   nan,   nan,   nan],
       [13.01, 18.  ,   nan,   nan,   nan,   nan],
       [14.99, 15.  ,   nan,   nan,   nan,   nan],
       [18.29, 22.  ,   nan,   nan,   nan,   nan],
       [ 9.22, 19.  ,   nan,   nan,   nan,   nan],
       [16.51,  7.  ,   nan,   nan,   nan,   nan],
       [15.32,  7.  ,   nan,   nan,   nan,   nan],
       [26.81, 14.  ,   nan,   nan,   nan,   nan],
       [24.91,  9.  ,   nan,   nan,   nan,   nan],
       [18.73, 13.  ,   nan,   nan,   nan,   nan]])

In [9]:
file[:,0]

array([27.05, 13.01, 14.99, ..., 32.05, 12.36, 10.45])

In [10]:
zdata = file[:,0]
xdata = file[:,1]

data = np.array([xdata])
zd = np.array([zdata])

In [11]:
data[:,8000]

array([6.])

In [12]:
d = np.zeros(data.size)
for i in range(data.size):
  d[i] = int(data[:,i])

In [13]:
int(d[45])

16

In [14]:
d = pd.get_dummies(d)

In [15]:
d

1.0   2.0   3.0   4.0   5.0   6.0   ...  20.0  21.0  22.0  23.0  24.0  25.0
0        0     0     0     0     0     0  ...     0     0     0     0     0     0
1        0     0     0     0     0     0  ...     0     0     0     0     0     0
2        0     0     0     0     0     0  ...     0     0     0     0     0     0
3        0     0     0     0     0     0  ...     0     0     1     0     0     0
4        0     0     0     0     0     0  ...     0     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
9995     0     0     0     0     0     0  ...     0     1     0     0     0     0
9996     0     0     0     0     0     0  ...     0     0     0     0     0     0
9997     0     0     0     0     0     0  ...     0     1     0     0     0     0
9998     0     0     0     0     0     0  ...     0     0     0     1     0     0
9999     0     0     0     0     0     0  ...     0     0     0     0     0     0

[10000 rows x 25 columns]

In [16]:
data = d

In [17]:
#zd = (zd-zd.min())/(zd.max())

In [18]:
zd[:5]

array([[27.05, 13.01, 14.99, ..., 32.05, 12.36, 10.45]])

In [19]:
data[:5]

1.0   2.0   3.0   4.0   5.0   6.0   ...  20.0  21.0  22.0  23.0  24.0  25.0
0     0     0     0     0     0     0  ...     0     0     0     0     0     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     0     0     0  ...     0     0     0     0     0     0
3     0     0     0     0     0     0  ...     0     0     1     0     0     0
4     0     0     0     0     0     0  ...     0     0     0     0     0     0

[5 rows x 25 columns]

In [20]:
data[:8000].shape

(8000, 25)

In [21]:
test_set_size = int(np.round(0.2*data.shape[1]));
train_set_size = data.shape[1] - (test_set_size);

In [22]:
x_train = data[:8000]
y_train = zd[:,:8000]

x_test = data[8000:]
y_test = zd[:,8000:]

In [23]:
x_train.shape

(8000, 25)

In [24]:
y_train.T.shape

(8000, 1)

In [25]:
x_train.shape

(8000, 25)

In [26]:
x_train = x_train
y_train = y_train.T
x_test = x_test
y_test = y_test.T

In [27]:
y_train.shape[1]

1

In [31]:
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.constraints import maxnorm
from keras.optimizers import Adam
from keras.layers.core import Dense, Dropout, Activation
'''
#build our model
model = Sequential()

model.add(Dense(25, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='Adam')

#build our model
model = Sequential()
model.add(Dense(250,input_dim=y_train.shape[1],kernel_initializer='normal', activation='relu'))
model.add(Dense(500,kernel_initializer='normal', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(250,kernel_initializer='normal', activation='relu'))
model.add(Dense(50,activation='softmax'))
# Compile model
optimizer = Adam(learning_rate=0.01, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
#optimizer = SGD(learning_rate=0.01, momentum=0)

'''

model = Sequential()
model.add(Dense(50,input_dim=y_train.shape[1]))
model.add(Activation('relu'))
model.add(Dense(500))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(25))
model.add(Activation('softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 50)                100       
_________________________________________________________________
activation_3 (Activation)    (None, 50)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 500)               25500     
_________________________________________________________________
activation_4 (Activation)    (None, 500)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 500)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 25)                12525     
_________________________________________________________________
activation_5 (Activation)    (None, 25)               

In [32]:
model.compile(loss='categorical_crossentropy', optimizer='ADAM', metrics=['accuracy'])

In [33]:
model.fit(y_train, x_train, batch_size=32, epochs=100,verbose=1)

Epoch 1/100
250/250 [==============================] - 7s 2ms/step - loss: 3.2768 - accuracy: 0.0412
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 3.0917 - accuracy: 0.0677
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 2.7820 - accuracy: 0.1505
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 2.3646 - accuracy: 0.2120
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 2.1439 - accuracy: 0.2741
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 2.0461 - accuracy: 0.2864
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 1.9407 - accuracy: 0.3147
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 1.8942 - accuracy: 0.3257
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 1.8173 - accuracy: 0.3495
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 1.7761 - accura

In [34]:
x_test[0:1]

1.0   2.0   3.0   4.0   5.0   6.0   ...  20.0  21.0  22.0  23.0  24.0  25.0
8000     0     0     0     0     0     1  ...     0     0     0     0     0     0

[1 rows x 25 columns]

In [ ]:
# Use scikit-learn to grid search the batch size and epochs
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
# Function to create model, required for KerasClassifier
def create_model():
  # create model
  model = Sequential()
  model.add(Dense(12, input_dim=y_train.shape[1], activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  # Compile model
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model


# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# define the grid search parameters
batch_size = [10, 20, 40, 60, 80, 100]
epochs = [10, 50, 100]
param_grid = dict(batch_size=batch_size, epochs=epochs)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(y_train,x_train)


# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

In [ ]:
# Use scikit-learn to grid search the learning rate and momentum
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.optimizers import Adam
# Function to create model, required for KerasClassifier
def create_model(learn_rate=0.01, momentum=0):
  # create model
  model = Sequential()
  model.add(Dense(25, input_dim=y_train.shape[1], activation='relu'))
  model.add(Dense(50, activation='relu'))
  model.add(Dense(25, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  # Compile model
  optimizer = Adam(lr=learn_rate, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
  model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
  return model

# create model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
learn_rate = [0.001, 0.01, 0.1, 0.2, 0.3]
param_grid = dict(learn_rate=learn_rate, momentum=momentum)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(y_train,x_train)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

In [35]:
score = model.evaluate(y_test,x_test)
print('Test score:', score[0])
print('Test accuracy:', score[1])

63/63 [==============================] - 1s 2ms/step - loss: 1.2163 - accuracy: 0.4855
Test score: 1.2162830829620361
Test accuracy: 0.4855000078678131


In [36]:
test_predictions = model.predict(y_test)

In [37]:
data2 = x_test

In [38]:
itemindex = numpy.where(data2==1)

In [39]:
itemindex[:10][1]+1

array([ 6,  2, 10, ..., 21, 23, 11])

In [40]:
for i in range(10):
  print("prediction classes",test_predictions[i].sum())

prediction classes 1.0
prediction classes 1.0
prediction classes 1.0000001
prediction classes 1.0
prediction classes 1.0
prediction classes 0.99999994
prediction classes 1.0
prediction classes 0.99999994
prediction classes 1.0
prediction classes 1.0


In [41]:
np.set_printoptions(precision=2)
for i in range(10):
  print("no",i+1, np.round(test_predictions[i],decimals=2) )

no 1 [0.   0.   0.   0.   0.   0.49 0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.02 0.   0.   0.   0.5  0.   0.  ]
no 2 [0.   0.09 0.02 0.   0.12 0.   0.1  0.   0.   0.07 0.   0.08 0.   0.
 0.08 0.   0.03 0.   0.   0.19 0.   0.   0.   0.   0.22]
no 3 [0.01 0.15 0.14 0.   0.   0.   0.07 0.01 0.   0.14 0.   0.06 0.   0.
 0.13 0.   0.25 0.   0.   0.   0.   0.01 0.   0.   0.  ]
no 4 [0.   0.08 0.01 0.   0.14 0.   0.08 0.   0.   0.09 0.   0.07 0.   0.
 0.09 0.   0.03 0.   0.   0.21 0.   0.   0.   0.   0.2 ]
no 5 [0.   0.15 0.06 0.   0.04 0.   0.1  0.   0.   0.2  0.   0.08 0.   0.
 0.19 0.   0.13 0.   0.   0.04 0.   0.   0.   0.   0.  ]
no 6 [0.04 0.18 0.27 0.   0.   0.   0.25 0.   0.   0.02 0.   0.18 0.   0.
 0.03 0.   0.01 0.01 0.   0.   0.   0.   0.   0.   0.01]
no 7 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.88
 0.   0.   0.   0.   0.   0.   0.12 0.   0.   0.   0.  ]
no 8 [0.   0.17 0.08 0.   0.02 0.   0.21 0.   0.   0.06 0.   0.17 0.   0.
 0.08 0

In [42]:
a = itemindex[:][1]+1

In [43]:
for i in range(10):
  b = test_predictions[i].argsort()[-5:][::-1]+1
  print("prediction classes",(b))
  print("answer",a[i])
  #print("prediction probabilities",test_predictions[i].sort()[-5:][::-1])
  print("associated var",y_test[i])

prediction classes [23  6 19 18 11]
answer 6
associated var [11.87]
prediction classes [25 20  5  7  2]
answer 2
associated var [15.14]
prediction classes [17  2 10  3 15]
answer 10
associated var [16.12]
prediction classes [20 25  5 15 10]
answer 5
associated var [15.25]
prediction classes [10 15  2 17  7]
answer 7
associated var [15.83]
prediction classes [ 3  7 12  2  1]
answer 12
associated var [14.53]
prediction classes [14 21  9 16 13]
answer 14
associated var [27.12]
prediction classes [ 7  2 12 25 15]
answer 25
associated var [14.89]
prediction classes [20 25  5 10 15]
answer 20
associated var [15.31]
prediction classes [23  6 19 18 11]
answer 6
associated var [11.9]


In [44]:
count = 0
for i in range(len(y_test)):
  b = test_predictions[i].argsort()[-5:][::-1]+1
  for j in range(5):
    if(b[j]==a[i]):
      count+=1

print("answer : ",count)

answer :  1850


In [45]:
print("accuracy : ",count/(len(y_test))*100 )

accuracy :  92.5
