<a href="https://colab.research.google.com/github/Parth7/ML-for-finance/blob/main/NN_VAR_data_Nevena_model_1_reversed_with_classes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

# Commonly used modules
import numpy as np
import os
import sys

# Images, plots, display, and visualization
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import cv2
import IPython
from six.moves import urllib
import random
print(tf.__version__)

2.5.0


In [2]:
from google.colab import files
uploaded = files.upload()

Saving cummulative_data_NN2.xls to cummulative_data_NN2.xls


In [3]:
file = pd.read_excel('cummulative_data_NN2.xls') 
# Data for three-dimensional scattered points


#(train_features, train_labels), (test_features, test_labels) = keras.datasets.boston_housing.load_data()

# get per-feature statistics (mean, standard deviation) from the training set to normalize by
#train_mean = np.mean(train_features, axis=0)
#train_std = np.std(train_features, axis=0)
#train_features = (train_features - train_mean) / train_std

In [4]:
file = file.to_numpy()

In [5]:
file[:10]

array([[13.99,  1.  ,   nan,   nan,   nan,   nan],
       [13.93,  1.  ,   nan,   nan,   nan,   nan],
       [13.81,  1.  ,   nan,   nan,   nan,   nan],
       [13.91,  1.  ,   nan,   nan,   nan,   nan],
       [13.81,  1.  ,   nan,   nan,   nan,   nan],
       [13.96,  1.  ,   nan,   nan,   nan,   nan],
       [14.06,  1.  ,   nan,   nan,   nan,   nan],
       [13.99,  1.  ,   nan,   nan,   nan,   nan],
       [13.92,  1.  ,   nan,   nan,   nan,   nan],
       [13.95,  1.  ,   nan,   nan,   nan,   nan]])

In [6]:
np.random.shuffle(file) 

In [7]:
file[:10]

array([[14.58, 28.  ,   nan,   nan,   nan,   nan],
       [14.98,  7.  ,   nan,   nan,   nan,   nan],
       [22.11, 36.  ,   nan,   nan,   nan,   nan],
       [ 7.42, 44.  ,   nan,   nan,   nan,   nan],
       [11.37, 34.  ,   nan,   nan,   nan,   nan],
       [15.14, 35.  ,   nan,   nan,   nan,   nan],
       [16.22, 42.  ,   nan,   nan,   nan,   nan],
       [15.92, 22.  ,   nan,   nan,   nan,   nan],
       [16.  , 42.  ,   nan,   nan,   nan,   nan],
       [14.77, 20.  ,   nan,   nan,   nan,   nan]])

In [8]:
file[:,0]

array([14.58, 14.98, 22.11, ..., 14.31, 11.8 , 11.75])

In [9]:
zdata = file[:,0]
xdata = file[:,1]

data = np.array([xdata])
zd = np.array([zdata])

In [10]:
data[:,8000]

array([37.])

In [11]:
d = np.zeros(data.size)
for i in range(data.size):
  d[i] = int(data[:,i])

In [12]:
int(d[45])

33

In [13]:
d = pd.get_dummies(d)

In [14]:
d

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
0        0     0     0     0     0     0  ...     0     0     0     0     0     0
1        0     0     0     0     0     0  ...     0     0     0     0     0     0
2        0     0     0     0     0     0  ...     0     0     0     0     0     0
3        0     0     0     0     0     0  ...     0     0     0     0     0     0
4        0     0     0     0     0     0  ...     0     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
9995     0     0     0     0     0     0  ...     0     0     0     0     0     0
9996     0     0     0     0     0     0  ...     0     0     0     0     0     0
9997     0     0     0     0     0     0  ...     0     0     0     0     0     0
9998     0     0     0     0     0     0  ...     0     0     0     0     0     0
9999     0     0     0     0     0     0  ...     0     0     0     0     0     0

[10000 rows x 50 columns]

In [15]:
data = d

In [16]:
#zd = (zd-zd.min())/(zd.max())

In [17]:
zd[:5]

array([[14.58, 14.98, 22.11, ..., 14.31, 11.8 , 11.75]])

In [18]:
data[:5]

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
0     0     0     0     0     0     0  ...     0     0     0     0     0     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     0     0     0  ...     0     0     0     0     0     0
3     0     0     0     0     0     0  ...     0     0     0     0     0     0
4     0     0     0     0     0     0  ...     0     0     0     0     0     0

[5 rows x 50 columns]

In [19]:
data[:8000].shape

(8000, 50)

In [20]:
test_set_size = int(np.round(0.2*data.shape[1]));
train_set_size = data.shape[1] - (test_set_size);

In [21]:
x_train = data[:8000]
y_train = zd[:,:8000]

x_test = data[8000:]
y_test = zd[:,8000:]

In [22]:
x_train.shape

(8000, 50)

In [23]:
y_train.T.shape

(8000, 1)

In [24]:
x_train.shape

(8000, 50)

In [25]:
x_train = x_train
y_train = y_train.T
x_test = x_test
y_test = y_test.T

In [26]:
y_train.shape[1]

1

In [27]:
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.constraints import maxnorm
from keras.optimizers import Adam
from keras.layers.core import Dense, Dropout, Activation
'''
#build our model
model = Sequential()

model.add(Dense(25, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='Adam')

#build our model
model = Sequential()
model.add(Dense(250,input_dim=y_train.shape[1],kernel_initializer='normal', activation='relu'))
model.add(Dense(500,kernel_initializer='normal', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(250,kernel_initializer='normal', activation='relu'))
model.add(Dense(50,activation='softmax'))
# Compile model
optimizer = Adam(learning_rate=0.01, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
#optimizer = SGD(learning_rate=0.01, momentum=0)

'''

model = Sequential()
model.add(Dense(50,input_dim=y_train.shape[1]))
model.add(Activation('relu'))
model.add(Dense(500))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(50))
model.add(Activation('softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                100       
_________________________________________________________________
activation (Activation)      (None, 50)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 500)               25500     
_________________________________________________________________
activation_1 (Activation)    (None, 500)               0         
_________________________________________________________________
dropout (Dropout)            (None, 500)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 50)                25050     
_________________________________________________________________
activation_2 (Activation)    (None, 50)                0

In [28]:
model.compile(loss='categorical_crossentropy', optimizer='ADAM', metrics=['accuracy'])

In [29]:
model.fit(y_train, x_train, batch_size=32, epochs=100,verbose=1)

Epoch 1/100
250/250 [==============================] - 16s 3ms/step - loss: 3.9898 - accuracy: 0.0180
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 3.8301 - accuracy: 0.0241
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 3.6412 - accuracy: 0.0486
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 3.1509 - accuracy: 0.1000
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 2.8146 - accuracy: 0.1632
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 2.5926 - accuracy: 0.1991
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 2.4533 - accuracy: 0.2295
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 2.3211 - accuracy: 0.2516
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 2.2560 - accuracy: 0.2627
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 2.1675 - accur

In [30]:
x_test[0:1]

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
8000     0     0     0     0     0     0  ...     0     0     0     0     0     0

[1 rows x 50 columns]

In [ ]:
# Use scikit-learn to grid search the batch size and epochs
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
# Function to create model, required for KerasClassifier
def create_model():
  # create model
  model = Sequential()
  model.add(Dense(12, input_dim=y_train.shape[1], activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  # Compile model
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
  return model


# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# define the grid search parameters
batch_size = [10, 20, 40, 60, 80, 100]
epochs = [10, 50, 100]
param_grid = dict(batch_size=batch_size, epochs=epochs)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(y_train,x_train)


# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

In [ ]:
# Use scikit-learn to grid search the learning rate and momentum
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.optimizers import Adam
# Function to create model, required for KerasClassifier
def create_model(learn_rate=0.01, momentum=0):
  # create model
  model = Sequential()
  model.add(Dense(25, input_dim=y_train.shape[1], activation='relu'))
  model.add(Dense(50, activation='relu'))
  model.add(Dense(25, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  # Compile model
  optimizer = Adam(lr=learn_rate, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
  model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
  return model

# create model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=10, verbose=0)
# define the grid search parameters
learn_rate = [0.001, 0.01, 0.1, 0.2, 0.3]
param_grid = dict(learn_rate=learn_rate, momentum=momentum)
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3)
grid_result = grid.fit(y_train,x_train)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

In [31]:
score = model.evaluate(y_test,x_test)
print('Test score:', score[0])
print('Test accuracy:', score[1])

63/63 [==============================] - 1s 2ms/step - loss: 1.4756 - accuracy: 0.4970
Test score: 1.4755610227584839
Test accuracy: 0.4970000088214874


In [32]:
test_predictions = model.predict(y_test)

In [33]:
data2 = x_test

In [34]:
itemindex = numpy.where(data2==1)

In [37]:
itemindex[:10][1]+1

array([37, 35, 28, ..., 28, 11, 11])

In [38]:
for i in range(10):
  print("prediction classes",test_predictions[i].sum())

prediction classes 1.0
prediction classes 1.0
prediction classes 1.0000001
prediction classes 1.0000001
prediction classes 1.0
prediction classes 1.0000001
prediction classes 0.99999994
prediction classes 1.0
prediction classes 1.0
prediction classes 0.9999999


In [39]:
np.set_printoptions(precision=2)
for i in range(10):
  print("no",i+1, np.round(test_predictions[i],decimals=2) )

no 1 [0.   0.01 0.19 0.   0.   0.   0.01 0.08 0.   0.   0.   0.   0.   0.
 0.05 0.   0.   0.   0.   0.02 0.   0.01 0.   0.   0.01 0.19 0.05 0.
 0.   0.   0.   0.14 0.   0.   0.   0.   0.16 0.   0.   0.   0.   0.08
 0.   0.   0.   0.   0.   0.   0.   0.  ]
no 2 [0.   0.08 0.   0.   0.03 0.   0.05 0.   0.   0.01 0.   0.08 0.   0.
 0.06 0.   0.06 0.   0.   0.05 0.   0.06 0.   0.   0.01 0.   0.05 0.01
 0.   0.04 0.   0.02 0.   0.   0.04 0.   0.   0.   0.   0.1  0.   0.
 0.   0.   0.14 0.   0.   0.   0.   0.11]
no 3 [0.   0.09 0.   0.   0.01 0.   0.07 0.   0.   0.   0.   0.1  0.   0.
 0.04 0.   0.08 0.   0.   0.04 0.   0.06 0.   0.   0.   0.   0.04 0.24
 0.   0.01 0.   0.01 0.   0.   0.01 0.   0.   0.   0.   0.04 0.   0.
 0.   0.   0.08 0.   0.   0.   0.   0.07]
no 4 [0.   0.05 0.   0.   0.06 0.   0.03 0.   0.   0.09 0.   0.05 0.   0.
 0.05 0.   0.04 0.   0.   0.04 0.   0.04 0.   0.   0.05 0.   0.04 0.
 0.   0.05 0.   0.03 0.   0.   0.07 0.   0.   0.   0.   0.11 0.   0.
 0.   0.   0.12 0.  

In [53]:
a = itemindex[:][1]+1

In [61]:
for i in range(10):
  b = test_predictions[i].argsort()[-5:][::-1]+1
  print("prediction classes",(b))
  print("answer",a[i])
  #print("prediction probabilities",test_predictions[i].sort()[-5:][::-1])
  print("associated var",y_test[i])

prediction classes [26  3 37 32 42]
answer 37
associated var [16.66]
prediction classes [45 50 40 12  2]
answer 35
associated var [15.1]
prediction classes [28 12  2 45 17]
answer 28
associated var [14.78]
prediction classes [45 40 10 50 35]
answer 7
associated var [15.31]
prediction classes [10 45 40 35 25]
answer 40
associated var [15.38]
prediction classes [10 25  5 35 15]
answer 40
associated var [15.64]
prediction classes [ 6 43 38 29 11]
answer 6
associated var [12.73]
prediction classes [26 37  3 32 42]
answer 22
associated var [16.77]
prediction classes [ 3 32 37 15 27]
answer 37
associated var [16.35]
prediction classes [10 45 40 50 35]
answer 30
associated var [15.35]


In [64]:
count = 0
for i in range(len(y_test)):
  b = test_predictions[i].argsort()[-5:][::-1]+1
  for j in range(5):
    if(b[j]==a[i]):
      count+=1

print("answer : ",count)

answer :  1621


In [65]:
print("accuracy : ",count/(len(y_test))*100 )

accuracy :  81.05
