<a href="https://colab.research.google.com/github/Parth7/ML-for-finance/blob/main/NN_VAR_data_Nevena_model_1_reversed_with_classes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

# Commonly used modules
import numpy as np
import os
import sys

# Images, plots, display, and visualization
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import cv2
import IPython
from six.moves import urllib
import random
print(tf.__version__)

2.5.0


In [3]:
from google.colab import files
uploaded = files.upload()

Saving cummulative_data_NN2.xls to cummulative_data_NN2.xls


In [4]:
file = pd.read_excel('cummulative_data_NN2.xls') 
# Data for three-dimensional scattered points


#(train_features, train_labels), (test_features, test_labels) = keras.datasets.boston_housing.load_data()

# get per-feature statistics (mean, standard deviation) from the training set to normalize by
#train_mean = np.mean(train_features, axis=0)
#train_std = np.std(train_features, axis=0)
#train_features = (train_features - train_mean) / train_std

In [5]:
file = file.to_numpy()

In [6]:
file[:10]

array([[13.99,  1.  ],
       [13.93,  1.  ],
       [13.81,  1.  ],
       [13.91,  1.  ],
       [13.81,  1.  ],
       [13.96,  1.  ],
       [14.06,  1.  ],
       [13.99,  1.  ],
       [13.92,  1.  ],
       [13.95,  1.  ]])

In [7]:
np.random.shuffle(file) 

In [8]:
file[:10]

array([[15.33, 35.  ],
       [30.3 , 24.  ],
       [18.6 , 47.  ],
       [14.66, 28.  ],
       [15.66, 37.  ],
       [15.23, 40.  ],
       [10.87, 16.  ],
       [13.24, 38.  ],
       [11.24, 34.  ],
       [14.41, 27.  ]])

In [9]:
file[:,0]

array([15.33, 30.3 , 18.6 , ..., 14.08, 16.19, 16.82])

In [10]:
zdata = file[:,0]
xdata = file[:,1]

data = np.array([xdata])
zd = np.array([zdata])

In [11]:
data[:,56]

array([49.])

In [12]:
d = np.zeros(data.size)
for i in range(data.size):
  d[i] = int(data[:,i])

In [13]:
int(d[45])

11

In [14]:
d = pd.get_dummies(d)

In [15]:
d

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
0        0     0     0     0     0     0  ...     0     0     0     0     0     0
1        0     0     0     0     0     0  ...     0     0     0     0     0     0
2        0     0     0     0     0     0  ...     0     0     1     0     0     0
3        0     0     0     0     0     0  ...     0     0     0     0     0     0
4        0     0     0     0     0     0  ...     0     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
9995     0     0     0     0     0     0  ...     0     0     0     0     0     0
9996     0     0     0     0     0     0  ...     0     0     1     0     0     0
9997     0     0     0     0     0     0  ...     0     0     0     0     0     0
9998     0     0     0     0     0     0  ...     0     0     0     0     0     0
9999     0     0     0     0     0     0  ...     0     0     0     0     0     0

[10000 rows x 50 columns]

In [16]:
data = d

In [17]:
#zd = (zd-zd.min())/(zd.max())

In [18]:
zd[:5]

array([[15.33, 30.3 , 18.6 , ..., 14.08, 16.19, 16.82]])

In [19]:
data[:5]

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
0     0     0     0     0     0     0  ...     0     0     0     0     0     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     0     0     0  ...     0     0     1     0     0     0
3     0     0     0     0     0     0  ...     0     0     0     0     0     0
4     0     0     0     0     0     0  ...     0     0     0     0     0     0

[5 rows x 50 columns]

In [20]:
data[:8000].shape

(8000, 50)

In [21]:
test_set_size = int(np.round(0.2*data.shape[1]));
train_set_size = data.shape[1] - (test_set_size);

In [22]:
x_train = data[:8000]
y_train = zd[:,:8000]

x_test = data[8000:]
y_test = zd[:,8000:]

In [23]:
x_train.shape

(8000, 50)

In [24]:
y_train.T.shape

(8000, 1)

In [25]:
x_train.shape

(8000, 50)

In [26]:
x_train = x_train
y_train = y_train.T
x_test = x_test
y_test = y_test.T

In [27]:
y_train.shape[1]

1

In [28]:
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.constraints import maxnorm
from keras.optimizers import Adam
from keras.layers.core import Dense, Dropout, Activation
'''
#build our model
model = Sequential()

model.add(Dense(25, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='Adam')

#build our model
model = Sequential()
model.add(Dense(250,input_dim=y_train.shape[1],kernel_initializer='normal', activation='relu'))
model.add(Dense(500,kernel_initializer='normal', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(250,kernel_initializer='normal', activation='relu'))
model.add(Dense(50,activation='softmax'))
# Compile model
optimizer = Adam(learning_rate=0.01, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
#optimizer = SGD(learning_rate=0.01, momentum=0)

'''

model = Sequential()
model.add(Dense(50,input_dim=y_train.shape[1]))
model.add(Activation('relu'))
model.add(Dense(500))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(50))
model.add(Activation('softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                100       
_________________________________________________________________
activation (Activation)      (None, 50)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 500)               25500     
_________________________________________________________________
activation_1 (Activation)    (None, 500)               0         
_________________________________________________________________
dropout (Dropout)            (None, 500)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 50)                25050     
_________________________________________________________________
activation_2 (Activation)    (None, 50)                0

In [29]:
model.compile(loss='categorical_crossentropy', optimizer='ADAM', metrics=['accuracy'])

In [41]:
model.fit(y_train, x_train, batch_size=128, epochs=50,verbose=1)

Epoch 1/50
63/63 [==============================] - 0s 7ms/step - loss: 1.4751 - accuracy: 0.4848
Epoch 2/50
63/63 [==============================] - 0s 6ms/step - loss: 1.4501 - accuracy: 0.4992
Epoch 3/50
63/63 [==============================] - 0s 6ms/step - loss: 1.4560 - accuracy: 0.5025
Epoch 4/50
63/63 [==============================] - 0s 6ms/step - loss: 1.4547 - accuracy: 0.4979
Epoch 5/50
63/63 [==============================] - 0s 6ms/step - loss: 1.4608 - accuracy: 0.4978
Epoch 6/50
63/63 [==============================] - 0s 6ms/step - loss: 1.4651 - accuracy: 0.4938
Epoch 7/50
63/63 [==============================] - 0s 6ms/step - loss: 1.4553 - accuracy: 0.4981
Epoch 8/50
63/63 [==============================] - 0s 6ms/step - loss: 1.4605 - accuracy: 0.4976
Epoch 9/50
63/63 [==============================] - 0s 6ms/step - loss: 1.4520 - accuracy: 0.5002
Epoch 10/50
63/63 [==============================] - 0s 6ms/step - loss: 1.4570 - accuracy: 0.4989
Epoch 11/50
63/63 [

In [42]:
x_test[0:1]

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
8000     0     0     0     0     0     0  ...     1     0     0     0     0     0

[1 rows x 50 columns]

In [43]:
score = model.evaluate(y_test,x_test)
print('Test score:', score[0])
print('Test accuracy:', score[1])

63/63 [==============================] - 0s 1ms/step - loss: 1.3783 - accuracy: 0.5140
Test score: 1.3782947063446045
Test accuracy: 0.5139999985694885


In [62]:
#from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D, GlobalAveragePooling2D, Flatten
from keras.layers.normalization import BatchNormalization

In [64]:
model = Sequential()                                 # Linear stacking of layers

# Convolution Layer 1
model.add(Conv2D(32, (1, 1),input_dim=y_train.shape[1])) # 32 different 3x3 kernels -- so 32 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
convLayer01 = Activation('relu')                     # activation
model.add(convLayer01)

# Convolution Layer 2
model.add(Conv2D(32, (3, 3)))                        # 32 different 3x3 kernels -- so 32 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
model.add(Activation('relu'))                        # activation
convLayer02 = MaxPooling2D(pool_size=(2,2))          # Pool the max values over a 2x2 kernel
model.add(convLayer02)

# Convolution Layer 3
model.add(Conv2D(64,(3, 3)))                         # 64 different 3x3 kernels -- so 64 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
convLayer03 = Activation('relu')                     # activation
model.add(convLayer03)

# Convolution Layer 4
model.add(Conv2D(64, (3, 3)))                        # 64 different 3x3 kernels -- so 64 feature maps
model.add(BatchNormalization(axis=-1))               # normalize each feature map before activation
model.add(Activation('relu'))                        # activation
convLayer04 = MaxPooling2D(pool_size=(2,2))          # Pool the max values over a 2x2 kernel
model.add(convLayer04)
model.add(Flatten())                                 # Flatten final 4x4x64 output matrix into a 1024-length vector

# Fully Connected Layer 5
model.add(Dense(512))                                # 512 FCN nodes
model.add(BatchNormalization())                      # normalization
model.add(Activation('relu'))                        # activation

# Fully Connected Layer 6                       
model.add(Dropout(0.2))                              # 20% dropout of randomly selected nodes
model.add(Dense(10))                                 # final 10 FCN nodes
model.add(Activation('softmax'))                     # softmax activation

ValueError: ignored