<a href="https://colab.research.google.com/github/Parth7/ML-for-finance/blob/main/NN_VAR_data_Nevena_model_1_reversed_with_classes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

# Commonly used modules
import numpy as np
import os
import sys

# Images, plots, display, and visualization
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import cv2
import IPython
from six.moves import urllib
import random
print(tf.__version__)

2.5.0


In [2]:
from google.colab import files
uploaded = files.upload()

Saving cummulative_data_NN2.xls to cummulative_data_NN2.xls


In [3]:
file = pd.read_excel('cummulative_data_NN2.xls') 
# Data for three-dimensional scattered points


#(train_features, train_labels), (test_features, test_labels) = keras.datasets.boston_housing.load_data()

# get per-feature statistics (mean, standard deviation) from the training set to normalize by
#train_mean = np.mean(train_features, axis=0)
#train_std = np.std(train_features, axis=0)
#train_features = (train_features - train_mean) / train_std

In [4]:
file = file.to_numpy()

In [5]:
file[:10]

array([[13.99,  1.  ],
       [13.93,  1.  ],
       [13.81,  1.  ],
       [13.91,  1.  ],
       [13.81,  1.  ],
       [13.96,  1.  ],
       [14.06,  1.  ],
       [13.99,  1.  ],
       [13.92,  1.  ],
       [13.95,  1.  ]])

In [6]:
np.random.shuffle(file) 

In [7]:
file[:10]

array([[17.41, 26.  ],
       [15.78, 27.  ],
       [10.26, 21.  ],
       [10.93, 16.  ],
       [16.33, 15.  ],
       [20.76,  9.  ],
       [32.32, 46.  ],
       [12.76,  6.  ],
       [16.16, 37.  ],
       [15.13,  2.  ]])

In [8]:
file[:,0]

array([17.41, 15.78, 10.26, ..., 21.34, 15.34, 15.58])

In [9]:
zdata = file[:,0]
xdata = file[:,1]

data = np.array([xdata])
zd = np.array([zdata])

In [22]:
data[:,56]

array([25.])

In [23]:
d = np.zeros(data.size)
for i in range(data.size):
  d[i] = int(data[:,i])

In [28]:
int(d[45])

40

In [31]:
d = pd.get_dummies(d)

In [32]:
d

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
0        0     0     0     0     0     0  ...     0     0     0     0     0     0
1        0     0     0     0     0     0  ...     0     0     0     0     0     0
2        0     0     0     0     0     0  ...     0     0     0     0     0     0
3        0     0     0     0     0     0  ...     0     0     0     0     0     0
4        0     0     0     0     0     0  ...     0     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
9995     0     0     1     0     0     0  ...     0     0     0     0     0     0
9996     0     0     0     0     0     0  ...     0     1     0     0     0     0
9997     0     0     0     0     0     0  ...     0     0     0     0     0     0
9998     0     0     0     0     0     0  ...     0     0     0     0     0     0
9999     0     0     0     0     0     0  ...     0     0     0     0     0     0

[10000 rows x 50 columns]

In [33]:
data = d

In [34]:
#zd = (zd-zd.min())/(zd.max())

In [35]:
zd[:5]

array([[17.41, 15.78, 10.26, ..., 21.34, 15.34, 15.58]])

In [36]:
data[:5]

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
0     0     0     0     0     0     0  ...     0     0     0     0     0     0
1     0     0     0     0     0     0  ...     0     0     0     0     0     0
2     0     0     0     0     0     0  ...     0     0     0     0     0     0
3     0     0     0     0     0     0  ...     0     0     0     0     0     0
4     0     0     0     0     0     0  ...     0     0     0     0     0     0

[5 rows x 50 columns]

In [47]:
data[:8000].shape

(8000, 50)

In [37]:
test_set_size = int(np.round(0.2*data.shape[1]));
train_set_size = data.shape[1] - (test_set_size);

In [48]:
x_train = data[:8000]
y_train = zd[:,:8000]

x_test = data[8000:]
y_test = zd[:,8000:]

In [49]:
x_train.shape

(8000, 50)

In [50]:
y_train.T.shape

(8000, 1)

In [52]:
x_train.shape

(8000, 50)

In [53]:
x_train = x_train
y_train = y_train.T
x_test = x_test
y_test = y_test.T

In [55]:
y_train.shape[1]

1

In [67]:
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.constraints import maxnorm
from keras.optimizers import Adam
from keras.layers.core import Dense, Dropout, Activation
'''
#build our model
model = Sequential()

model.add(Dense(25, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(25, activation='relu'))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='Adam')

#build our model
model = Sequential()
model.add(Dense(250,input_dim=y_train.shape[1],kernel_initializer='normal', activation='relu'))
model.add(Dense(500,kernel_initializer='normal', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(250,kernel_initializer='normal', activation='relu'))
model.add(Dense(50,activation='softmax'))
# Compile model
optimizer = Adam(learning_rate=0.01, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
#optimizer = SGD(learning_rate=0.01, momentum=0)

'''

model = Sequential()
model.add(Dense(512,input_dim=y_train.shape[1]))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(50))
model.add(Activation('softmax'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 512)               1024      
_________________________________________________________________
activation_3 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_9 (Dense)              (None, 512)               262656    
_________________________________________________________________
activation_4 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_10 (Dense)             (None, 50)               

In [68]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [75]:
model.fit(y_train, x_train, batch_size=32, epochs=100,verbose=1)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 1.7692 - accuracy: 0.3749
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 1.7453 - accuracy: 0.3795
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 1.7296 - accuracy: 0.3816
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 1.7107 - accuracy: 0.3906
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 1.7206 - accuracy: 0.3853
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 1.7009 - accuracy: 0.3911
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 1.6992 - accuracy: 0.3984
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 1.7010 - accuracy: 0.3955
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 1.7083 - accuracy: 0.3980
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 1.6980 - accura

In [61]:
x_test[0:1]

1.0   2.0   3.0   4.0   5.0   6.0   ...  45.0  46.0  47.0  48.0  49.0  50.0
8000     0     0     0     0     0     0  ...     0     0     0     0     0     0

[1 rows x 50 columns]

In [72]:
score = model.evaluate(y_test,x_test)
print('Test score:', score[0])
print('Test accuracy:', score[1])

63/63 [==============================] - 1s 2ms/step - loss: 1.4854 - accuracy: 0.4930
Test score: 1.4854400157928467
Test accuracy: 0.49300000071525574
