<a href="https://colab.research.google.com/github/Parth7/ML-for-finance/blob/main/NN_VAR_data_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

# Commonly used modules
import numpy as np
import os
import sys

# Images, plots, display, and visualization
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import cv2
import IPython
from six.moves import urllib
import random
print(tf.__version__)

2.5.0


In [2]:
from google.colab import files
uploaded = files.upload()

Saving cummulative_data_NN2.xls to cummulative_data_NN2.xls


In [3]:
file = pd.read_excel('cummulative_data_NN2.xls') 
# Data for three-dimensional scattered points


#(train_features, train_labels), (test_features, test_labels) = keras.datasets.boston_housing.load_data()

# get per-feature statistics (mean, standard deviation) from the training set to normalize by
#train_mean = np.mean(train_features, axis=0)
#train_std = np.std(train_features, axis=0)
#train_features = (train_features - train_mean) / train_std

In [4]:
file = file.to_numpy()

In [5]:
file[:10]

array([[ -8.85993485,   1.        ],
       [ -9.25081433,   1.        ],
       [-10.03257329,   1.        ],
       [ -9.38110749,   1.        ],
       [-10.03257329,   1.        ],
       [ -9.05537459,   1.        ],
       [ -8.40390879,   1.        ],
       [ -8.85993485,   1.        ],
       [ -9.31596091,   1.        ],
       [ -9.12052117,   1.        ]])

In [6]:
np.random.shuffle(file) 

In [7]:
file[:10]

array([[  0.        ,   5.        ],
       [-51.46579805,  44.        ],
       [110.29315961,  46.        ],
       [  0.45602606,  15.        ],
       [  2.21498371,  20.        ],
       [  3.38762215,  20.        ],
       [-10.03257329,  33.        ],
       [  7.16612378,   3.        ],
       [ -1.56351792,  45.        ],
       [104.23452769,  46.        ]])

In [8]:
file[:,0]

array([  0.        , -51.46579805, 110.29315961, ...,   1.10749186,
         1.56351792,  -0.6514658 ])

In [9]:
zdata = file[:,0]
xdata = file[:,1]

data = np.array([xdata])
zd = np.array([zdata])

In [10]:
test_set_size = int(np.round(0.2*data.shape[1]));
train_set_size = data.shape[1] - (test_set_size);

In [11]:
x_train = data[:,:train_set_size]
y_train = zd[:,:train_set_size]

x_test = data[:,train_set_size:]
y_test = zd[:,train_set_size:]

In [12]:
x_train[:15]

array([[ 5., 44., 46., ...,  7., 17.,  5.]])

In [13]:
train_features = x_train

In [14]:
y_train.T.shape

(8000, 1)

In [15]:
x_train.T.shape

(8000, 1)

In [16]:
x_train = x_train.T
y_train = y_train.T
x_test = x_test.T
y_test = y_test.T

In [17]:
#Define training hyperprameters.
batch_size = 50
num_epochs = 200
learning_rate = 0.01
size_hidden= 20

#Calculate some other hyperparameters based on data.  
batch_no = len(y_train) // batch_size  #batches
cols=y_train.shape[1] #Number of columns in input matrix
n_output=1

In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [20]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

#build our model
model = Sequential()

model.add(Dense(50, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(2))

model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model
model.fit(
    y_train,
    x_train,
    epochs=500,
    shuffle=True,
    verbose=2
)

Epoch 1/500
250/250 - 1s - loss: 387.3839
Epoch 2/500
250/250 - 0s - loss: 190.1146
Epoch 3/500
250/250 - 0s - loss: 183.7361
Epoch 4/500
250/250 - 0s - loss: 180.7479
Epoch 5/500
250/250 - 0s - loss: 181.8225
Epoch 6/500
250/250 - 0s - loss: 179.7695
Epoch 7/500
250/250 - 0s - loss: 178.1023
Epoch 8/500
250/250 - 0s - loss: 178.1773
Epoch 9/500
250/250 - 0s - loss: 177.1139
Epoch 10/500
250/250 - 0s - loss: 177.1387
Epoch 11/500
250/250 - 0s - loss: 175.8397
Epoch 12/500
250/250 - 0s - loss: 176.9456
Epoch 13/500
250/250 - 0s - loss: 178.1492
Epoch 14/500
250/250 - 0s - loss: 176.8522
Epoch 15/500
250/250 - 0s - loss: 176.3117
Epoch 16/500
250/250 - 0s - loss: 177.3142
Epoch 17/500
250/250 - 0s - loss: 175.6453
Epoch 18/500
250/250 - 0s - loss: 175.3683
Epoch 19/500
250/250 - 0s - loss: 174.9545
Epoch 20/500
250/250 - 0s - loss: 175.7434
Epoch 21/500
250/250 - 0s - loss: 175.1405
Epoch 22/500
250/250 - 0s - loss: 175.3153
Epoch 23/500
250/250 - 0s - loss: 176.1991
Epoch 24/500
250/250

In [21]:
x_test[1].T

array([18.])

In [22]:
x_test[0:1]

array([[18.]])

In [23]:
y_test[0:1]

array([[22.28013029]])

In [25]:
a = [1,2,3,4,5,6,7,8,9];
for i in a: 
  prediction = model.predict(y_test[i-1:i])
  y_0 = prediction[0][0]
  print('Prediction - {}',format(y_0))
  print('Actual',x_test[i-1:i])

Prediction - {} 21.002824783325195
Actual [[18.]]
Prediction - {} 26.70868492126465
Actual [[18.]]
Prediction - {} 38.755863189697266
Actual [[39.]]
Prediction - {} 21.129697799682617
Actual [[19.]]
Prediction - {} 9.78196907043457
Actual [[33.]]
Prediction - {} 26.6373291015625
Actual [[41.]]
Prediction - {} 33.269161224365234
Actual [[34.]]
Prediction - {} 21.85772132873535
Actual [[10.]]
Prediction - {} 25.730024337768555
Actual [[24.]]
